spring.application.name: user-service
server.port: 8000
security.basic.enabled: false
eureka:
  client.serviceUrl.defaultZone: ${eureka.url:http://localhost:8761}/eureka
  instance:
    preferIpAddress: true

spring:
  data:
    mongodb:
      host: ${mongo.host:localhost}
      database: movies

jwt.secret.key: m0vi3s@pp

